### ISSUE TITLE
Making AboutUs page

### ISSUE THREAD

**Issue by nmtoan251998** [nmtoan251998/coders.tokyo.cantho-quizapp#5]
### Purpose
Using as an annual introduction of the beginning of the OfflineStudy to new members (also regular members)
### Specification
- Requirement: Show all the purpose of the OfflineStudy group 
  - Who we are?
  - How do we work?
  - What did we do?
  - What do you get from this group?
  - What things are required when you come to this group? 
  - What you need to do to perform 'best' status in this group?)
- Wireframe: (need help to design the wireframe to layout the page)

**Comment by nghipq** [comment]
Cho em ké phần này nha anh, em là Nghị :3

**Comment by nmtoan251998** [comment]
> Cho em ké phần này nha anh, em là Nghị :3

Ok em ơi. Em làm mẫu cái wireframe rồi gửi anh em trong team coi thảo luận cùng nha

**Comment by nghipq** [comment]
dạ
